#application.properties

spring.application.name=gym-backend
server.port = 8091
server.error.include-stacktrace=never

#Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gym-backend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

#Credenciales de la base de datos
spring.datasource.username = root
spring.datasource.password =

#Credenciales de Google OAuth2
google.client.id=397777478100-8m0sbqbc5d79pj4c0a4vba3ecr2m0o6s.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:5173/auth/login

#Para que en el login pida email and password
spring.security.oauth2.client.registration.google.client-id=397777478100-8m0sbqbc5d79pj4c0a4vba3ecr2m0o6s.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

#Driver de conexion (ultima version con el cj)
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
#JDBC significa Java Database Connectivity (Conectividad de Bases de Datos de Java).

#Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect

#Configuracion de seguridad para JWT
jwt.secret = unaClaveSecretaMuyLargaYSeguraParaFirmarElToken123456
jwt.expiration = 3600000